apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-app-ingress
  labels:
    app.kubernetes.io/name: sample-app-ingress
spec:
  ingressClassName: traefik
  rules:
  - host: sample-k8s-fast-taint.mattuu.com
    http:
      middlewares:
        ui-stripprefix:
          stripPrefix:
            prefixes:
              - "/ui"
      paths:
        - path: /ui
          pathType: Prefix
          backend:
            service:
              name: sample-frontend-service
              port: 
                number: 80
        - path: /app
          pathType: Prefix
          backend:
            service:
              name: sample-backend-service
              port: 
                number: 80
