apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sample-taint-hostname
resources:
  - ./backend.yaml
  - ./frontend.yaml
  - ./backend-service.yaml
  - ./frontend-service.yaml
  - ./middleware.yaml
  - ./ingressroute.yaml
  # - ./ingress.yaml
